# Generated by Django 5.1.7 on 2025-04-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_product_description_alter_product_price_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
